### ISSUE TITLE
rimeX: HOME DEFAULT for Windows

### ISSUE THREAD

**Issue by perrette** [iiasa/rime#14]
Right now HOME default is set according to Linux standard. Windows standard needed. @mwerning

**Comment by perrette** [comment]
The fix should happen in [rimeX/config.py](https://github.com/iiasa/rime/blob/33b0aa0073cc83dfe7da88adb6c52497e3716341/rimeX/config.py#L20-L23)

**Comment by mwerning** [comment]
Fix works for me.

**Comment by perrette** [comment]
Great! Thanks for trying it out. I'll close the issue as resolved, then.
