### ISSUE TITLE
Collection of usability issues with rimeX 

### ISSUE THREAD

**Issue by NiklasSchwind** [iiasa/rime#23]
- Add option to process yearly data
- Add "ensemble" column to records 
- Add an automatic model democracy/ensemble democracy weighting option to the emulator function call, either as True or False or as weights for a dict with weights for each model or ensemble member in the dataset. Keep the possibility to weight individual simulations in csv file, but give the possibility to rename the weighting column. Like this one only needs one dataset for different weighting options according to different criteria, e.g. if tipping points are triggered in a simulation. 
- add an option to add a custom function to preprocess climate variables before inputting it into rime preprocessing? 

- The isimip download script ignore 1850 to 1860 and rcp4.5 for isimip2

**Comment by perrette** [comment]
- preprocessing: mask for subregions (e.g. state in the US) are ignored. Bring them back !

**Comment by perrette** [comment]
I close now since I split these points into single issues regrouped into a [milestone](https://github.com/iiasa/rime/milestone/1).
